time-machine-password: ENC[AES256_GCM,data:um1ZModAJ2A=,iv:alnk94xIgADVIDYKCWMjCLE/0Iliis3UaDM4N0yVEFE=,tag:iCE6ENlFtKAkCIUx+X17Ug==,type:str]
harmonia-signing-key: ENC[AES256_GCM,data:1VKfQ3u2bE/o5TeozYJ2z49zIfWh3u0wW7gAfyXkWBJlI1ozj1kgENaq5WMfoui/kjOtJ37fsvnJM6wQc3CyHnCAf8NNnboAIqF7d+KLqtToUJllywuB5iTS5J1utzuYLGd8T3iGkl4g0IY=,iv:RynQgFjJzm1TGAH6pRawUVpGsgXqJfEvALUKSyjbZyg=,tag:ByA8rmJKFKQSrYE1nuDb3w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL1hSOWxjOHFTc0N1dk0z
        Q1AyQjBjUTlSUGRXWk5pK0RaSGwrQmpmckVrCm5xcFFQUzVEeTlMbE9VYldObTFy
        dmlhSUpWd21yeUZSR0QzNDdKbTh2Nk0KLS0tIFpoZkpJdnd3N293Ti9wUC9IQ0ZV
        TlEzQVFsTkV3WVFjVW9qcDhVVGpHRmcKZfw1n+pgSqZY+LGqlAbXMr9P6slVrn03
        rHz+MrpwDms91tr9efQWnuvg56PIWGie9VIAqBfleDx0dd2xnqsN9Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1547vqtqhgtxu54eewxwttjsfd85w0lm4f46fyxxhnx2ydxt7kyxs36ts2d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcEJuVitsRCsxZW1WVHkx
        eUpkMzVUTkpzK0IrVzBaaVk5Tkt5RWpPaHlFCnpRQm5mNGFDelV4TFZzeXczV3Rj
        UVA0bmx5eFdtN1BiWUhQdkx0MjJ6MHMKLS0tIGVJM2Fjdm0xa29Dc1ZIdGFPSHZq
        Tnp5ck5TcmJoOUVBUlVCQ0RCNUt4SzQKhnRlqtnLjtvq6znFJtDzXaFNtW2UK4tu
        HaU2D2pR5rCrGgq2UIr5qDnqE1yrHScGrvq8bo9pvXSJmaOgWrTN1Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xxpd2a56xjj9kzx7xt2ax6w36a68vtzcd8enrnvup6m6wfr6upwq8fr5h5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBob1orRnpNZENJNzVQd04w
        SDBmSng4Uy9Odk9JbE9NZU1GajM3ZG85Q1VrClZhUDl0b2JUUklRWlM0TmVZSlNN
        YVo0WU5yMTIyR3piY3dDTUkyK2FPN3cKLS0tIHRWQUIrL296anhoWDZWS0g2WFdZ
        ZHZDZTI1cjkrWWFXY09ITVhTcFhZc0EKEgo5ewzklVqhM7I+azJj3jwd+HtcHw2h
        4RdK6aIKIbo4Lyq0YNc9tKcRmktRkXijcRzcSzl2xsOoC8K7UUluMg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1q2qaahrx4chvsa5g7xqwrwk28mld6kn4md8crcrqg046m8yt2efsugl8vr
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQVM5WGJGZ2F1Qnk0RnhR
        WDcrWDg2WHRKRXczVGNyTjNCdzZpOG9tTm00CmQ1Z3lFUW5NSzNmOWhGai9ZREZX
        MTRZZzV6RDRSNXk1RWFyUmpaY0dCS3cKLS0tIFBVNitxQlgyR0xnTUlKdGlPY1I1
        endQcmlPc0EvZEozNmFVNDFSNjBSWU0KugT1EomyxQMR51LzGiokbfeG9h+gikMy
        /MnLlNpsbOb7FNB6WLXh78cMUwrZXDiHzhjia6iziSerCU+zNrBZkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1aqgjd4qsf8j08wg6l9f38hhckm7hl7mtkc9jnrxqxytt6j68qg9szs4e25
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWWxYS1Vqa3NYellVOTBZ
        K3hnUGlwMEFTQVNhTVg3MTh1R2xTZ2tVenp3CjlsZ0ZOOXUweldweEZxS3RjeHZk
        dFhPOXJBcm9lUWRBdHVBMEJBbkd5YXMKLS0tIFZKKzdXNVlPank3SVVrWVN2UDl0
        Zjl4eU8wTTdZRlhrdmlpZ1lmNTk2M0UKLx/DCj+7B2CKkii+19cbubOjGmXC1cnC
        f2ASH0AupBeRlI98/RIWwybTxZobAxfQLPosBID0ibu4xvtFs86png==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wdcttrjd379j0y5uzc2hslulk0tdynykq8tuh0f3q63qxkqc9ghqurtw6a
  lastmodified: "2026-09-14T03:21:29Z"
  mac: ENC[AES256_GCM,data:zfzbqocVeeq05nQPEbBXI7jS/OTgrdWR0eIT0EtWGDdMogi7KGz29tMco4sWr0+V6piL9Or+4ITEsdNTkXybBa1lGRG0XcCvfTDQ9rET4Y0+y9v/Ibs0P62eHM4a0jbvnfbKYPoOXONV5VsgNGEza166pNnlQxuS2KL4KuHyld0=,iv:iWjroCMgd6PefYnz1lQVH2wf/iYGJuUIm+1pVVflqGQ=,tag:K3AMTe7cOgwI3z/CeKeGIw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
