time-machine-password: ENC[AES256_GCM,data:um1ZModAJ2A=,iv:alnk94xIgADVIDYKCWMjCLE/0Iliis3UaDM4N0yVEFE=,tag:iCE6ENlFtKAkCIUx+X17Ug==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbU1ZcUVsOFFkWDJvQ002
        dTR2N0Y5aFFzUm93cUpDakg3S3l6SHEyYlNBCjBOcVZuME02a204cW5pMlAxU2Q4
        ZmVNYXdSYXBYYnJtSHBEM1Z4WW1zRUUKLS0tIGxIbEJidFl5S0M1ejBsVkxwUEUy
        TnIvODBMS1Zzc1BKNENKVTdER0poSXMKDU3tDqkVoG1J4fwKJLih+rp1yiFXR3Ap
        rY6waMd4jV30W8FA1V+5RlRk2BDj3b5fLTkXPRE1nlBdrjz8jl7NhA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1547vqtqhgtxu54eewxwttjsfd85w0lm4f46fyxxhnx2ydxt7kyxs36ts2d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZmFQZmFHcVlBc2NIZWtC
        QUdVY0JKRno2bHhxMDJLNmUzWUsrMjhwUUZRCktHSUZVclR4dEt4WTVyR0htbzdP
        eDBaelRhaE05c3RVVk5rc2F2SGVhV2cKLS0tIHZnY21lOGlNaXVyYlB0Y0djRyto
        aG1MSjJiNnphSWV3cUVYMUM3UmwrNXcKWQjnJlWk4HnoyFI43tiKGuhTX4FfYvTB
        Nq5hT91MD8/URLnCWvoWhk4iDFFUrwaWFJsyvPD2j5BgSq2ePmf9Yw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xxpd2a56xjj9kzx7xt2ax6w36a68vtzcd8enrnvup6m6wfr6upwq8fr5h5
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQ01PcmNmUWluWGFWNWNy
        WktLWDNoMGE2ZkJjTGVZR0tYbE9wQWVXYlU4CnVRSFRGeml1b0FqMFlvYmhFZE54
        aVZFZlNSYU1OSVNINXJ4dzRIWXRRSWMKLS0tIC9GSlUxV3Juc2dodVJoanVDNXlW
        dkR1OUNHY2FSSlRKSUh5RVp1em1oNzAK4knsM02JljudSYL2w7EkOdtpHWbizxea
        loVenRI5CKNH1VU9PVwCGDpXRnMSOXW0xxledEj+fhWTtP6Ve/QeMA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1q2qaahrx4chvsa5g7xqwrwk28mld6kn4md8crcrqg046m8yt2efsugl8vr
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURHErOUV1NTB4Rms3U2tU
        WFUzWUVOWUwvdDdBaUk3SFYxdWlvSWRRZ2pVCjlZQXFjVEdxN0psbDJEWDRTR2RC
        Qnh5NGd0N2lNbnJweG1FbDY4Nm1PUTAKLS0tIElYRGF5YUR1dXhURFZOOEtXTXJI
        ZElCNGZ0UkhKU3RYc3dtQWlpcFlyUk0KZ/GtfRZQ5YrbukS7/N4ywutbvsP+aKDu
        bVzZA+aJ1DAPp08BSgUM2lnUpjiMPQTxdacRCDrpE1AMJ+j+dK9MlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1aqgjd4qsf8j08wg6l9f38hhckm7hl7mtkc9jnrxqxytt6j68qg9szs4e25
  lastmodified: "2026-08-17T01:09:26Z"
  mac: ENC[AES256_GCM,data:GXZJHgrTttHMRXEH0XO75SyVrDSQCifu7ZCMMKGuMZjRmi0hzoBdeXlrNX/hIViqafJqQ3/tlB5b+wCHqMerzGO7G0pimPDprGlQNBmHx7RBHp8abG0tzHcGou0EWTQoFQyyNr7LzzbRatmfY5yHyNxk2V4dGip7GfKBmdP3qQE=,iv:7GOk/CN282ueTaVUYhJgPvKtqUkiy5w0Y5NPiPH+Igo=,tag:nqRDfoHd6OdyFaYHWCbmlQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
