nut-password: ENC[AES256_GCM,data:uR8eKFeGitNvR121lXsJtXJt3YwfliNo84jaZ+NJufA=,iv:iJ6m/J0scXppkZ2DiEFzcxsh6BiBxCxG0jp1134KLtY=,tag:n6LYNtU1Diwpt8eLo8/1fQ==,type:str]
harmonia-signing-key: ENC[AES256_GCM,data:S7Lj4Rreg7sbWXdnSdz9EineuypQYo6IILGh4gV2VUEXx2mqYCboaNLF87RBSvyndJWI31bw0x+NddMXNUW3JzQ6DuKUn0M3MjfMv+jycLXo9bTDp7AbSM9dqtzvlrFTuor2FuxrRUQZTsI=,iv:3+41N6wrMdzN1LgoBFPG9vLnvud30b1Ux5XvKe5DwKo=,tag:nAY9RHRvVVfnfVClYLniJw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMk5ZaHUwV2RzdGFXTkdO
        THRlVnZFcVh6UElHbWU0Q3QxRGZ5d214YXdJCjlXczd5bTBWT0RqTys2eEJsUFdk
        bU1ONzgzZHFHL0Y5TG5uYTBicWpuKzgKLS0tIEt4TEpiUFJjRGJTQjVOMHYva0xz
        R0lEa0syakVuU29SUXhXK3FhMjgxZGsKQZc4GXI9E2oNY9ukeIKeLKGVMs5IIZ2i
        obZN64SEMpivP29rL7xeSGfEkmfYpHy4FXqbSOjYpzsjXNZZREX5dA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1547vqtqhgtxu54eewxwttjsfd85w0lm4f46fyxxhnx2ydxt7kyxs36ts2d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcUZTV1o4TmN4Vmk4U1lB
        MStFV3N3d1VyZ1ZOMHVNb3hwUHdXUytzQnprCkVBQ1J5MnVtWnllUG10c1Jqa2Fy
        WGdhdzBGOTIvVUsxK1BETUFzdndVZ2sKLS0tIE9vTWJZdDdLcE5Ca0ZBQTAyaEZp
        Tno1bkphREtqYXlBQnk2KzhLU256SlEKHH4lzsesgegD0+Wckeg2dlCeK+C1n+p3
        v/SXqIv8ilRC2wj479QUQMLSei+jfgFqYuUAuZRlhsGDM97ac5zMtw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13xfa77f49ne56z3yyqh9qc9upjmrjfva8kcvg3jfem2m99dhr9fs34gdrp
  lastmodified: "2026-09-14T02:17:14Z"
  mac: ENC[AES256_GCM,data:Um4XzNx55bcnk3kVFesER6sKCXpdQaH7EIqwhveGbt1+Ww1ZUsLfkPvQb/lm7Phkhf3+wg+mNAm6WKBcCVQ5m3Y5r5Ulh2HQ6yHkcNVN5ou1OUdkjIShha+6G8uN3hwj2I2zD1+ART5YLvduWbzIv9CnX+JlEm8eZziTZNhM80s=,iv:gWS1GIWfZFj0M0qXHLLBP7b3qm4M48Pq4tMixV1rXwA=,tag:YGnqxcxM+6WR4OXsOl0e0w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
