nut-password: ENC[AES256_GCM,data:uR8eKFeGitNvR121lXsJtXJt3YwfliNo84jaZ+NJufA=,iv:iJ6m/J0scXppkZ2DiEFzcxsh6BiBxCxG0jp1134KLtY=,tag:n6LYNtU1Diwpt8eLo8/1fQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMk5ZaHUwV2RzdGFXTkdO
        THRlVnZFcVh6UElHbWU0Q3QxRGZ5d214YXdJCjlXczd5bTBWT0RqTys2eEJsUFdk
        bU1ONzgzZHFHL0Y5TG5uYTBicWpuKzgKLS0tIEt4TEpiUFJjRGJTQjVOMHYva0xz
        R0lEa0syakVuU29SUXhXK3FhMjgxZGsKQZc4GXI9E2oNY9ukeIKeLKGVMs5IIZ2i
        obZN64SEMpivP29rL7xeSGfEkmfYpHy4FXqbSOjYpzsjXNZZREX5dA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1547vqtqhgtxu54eewxwttjsfd85w0lm4f46fyxxhnx2ydxt7kyxs36ts2d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcUZTV1o4TmN4Vmk4U1lB
        MStFV3N3d1VyZ1ZOMHVNb3hwUHdXUytzQnprCkVBQ1J5MnVtWnllUG10c1Jqa2Fy
        WGdhdzBGOTIvVUsxK1BETUFzdndVZ2sKLS0tIE9vTWJZdDdLcE5Ca0ZBQTAyaEZp
        Tno1bkphREtqYXlBQnk2KzhLU256SlEKHH4lzsesgegD0+Wckeg2dlCeK+C1n+p3
        v/SXqIv8ilRC2wj479QUQMLSei+jfgFqYuUAuZRlhsGDM97ac5zMtw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13xfa77f49ne56z3yyqh9qc9upjmrjfva8kcvg3jfem2m99dhr9fs34gdrp
  lastmodified: "2026-08-05T00:59:34Z"
  mac: ENC[AES256_GCM,data:7HF8KXRfc21NrotV0ZsqvFU6R2GBMVq0Ax1Az9sjJysPbQ3QJ7LOZpYXKt3TX/zk2fGQSxioPwi8F5omGgzEUW1xFkGxlF3tyiuXGoEPAIHUl7YQGUpna3LYo2H197AdUIoNl+71IjGXBPfEO8a9Lg1BN8q4jS3Bzcbifc8AuWw=,iv:d5oULDX2ep5eVHXvitC33eoLDV6gNC5Qt29FYyv7Ukg=,tag:NV8rRvDb6jlW9xgASUvSxw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
