#!/usr/bin/env python3
"""Mine an AgentsView archive for recurring corrections, routing gaps, and
harness signals, and trace instruction-file provenance.

Unlike ai_session_audit.py, this lane reads prompt and reply text. It opens the
archive read-only and writes derived artifacts only under the caller's --out
directory with owner-only permissions. Exit codes: 0 success, 1 failure, 2
invalid input.
"""

from __future__ import annotations

import argparse
import collections
import datetime as dt
import json
import os
import re
import sqlite3
import subprocess
import sys
from collections.abc import Iterable, Sequence
from pathlib import Path
from typing import Any

DESCRIPTION = "Mine an AgentsView archive for agent-history retrospectives."
DEFAULT_DB = Path.home() / ".agentsview" / "sessions.db"
DEFAULT_TRIGGERS = (
    Path(__file__).resolve().parents[1] / "assets" / "routing-triggers.json"
)
DEFAULT_AGENTS = ("claude", "codex", "antigravity-cli", "gemini", "opencode")
DEFAULT_INSTALLED_ROOTS = (
    r"\.config/codex/skills",
    r"\.codex/skills",
    r"\.agents/skills",
    r"/skills/\.system",
    r"\.config/claude/skills",
)

# --- Prompt cleaning -------------------------------------------------------

WRAPPER_BLOCKS = [
    re.compile(r"<T3_WORKSPACE_CONTEXT>.*?</T3_WORKSPACE_CONTEXT>", re.DOTALL),
    re.compile(r"<system-reminder>.*?</system-reminder>", re.DOTALL),
    re.compile(r"<image name=[^>]*>\s*</image>", re.DOTALL),
    re.compile(r"<local-command-caveat>.*?</local-command-caveat>", re.DOTALL),
]
IMAGE_TOKEN = re.compile(r"\[Image #?\d+\]")
OPENCODE_MODE = re.compile(r"^\s*\[(search|analyze)-mode\].*?\n---\n", re.DOTALL)
# OpenCode inlines @-mentioned files after the typed prompt.
OPENCODE_INLINED = re.compile(
    r"\nCalled the \w+ tool with the following input:.*\Z", re.DOTALL
)
CODEX_REQUEST = re.compile(r"^.*?## My request for Codex:\s*", re.DOTALL)
COMMAND_NAME = re.compile(r"<command-name>\s*(/[^<\s]+)\s*</command-name>")
COMMAND_ARGS = re.compile(r"<command-args>(.*?)</command-args>", re.DOTALL)
INJECTED = [
    re.compile(pattern, re.DOTALL)
    for pattern in (
        r"^\s*<hook_prompt",
        r"^\s*Warning: apply_patch was requested via exec_command",
        r"^\s*\[SYSTEM DIRECTIVE",
        r"^\s*\[SYSTEM REMINDER",
        r"^\s*\[ALL BACKGROUND TASKS COMPLETE\]",
        r"^\s*You write concise thread titles",
        r"^\s*<local-command-std(out|err)>",
        r"^\s*<bash-std(out|err)>",
        r"^\s*<task-notification>",
        r"^\s*Caveat: The messages below were generated by the user while running local commands",
        r"^\s*This session is being continued from a previous conversation",
        r"^\s*\[Request interrupted by user",
        r"^\s*<environment_context>",
        r"^\s*# AGENTS\.md instructions for",
        r"^\s*<user_instructions>",
        r"^\s*<turn_aborted>",
    )
]
# Worker reports, plugin notices, and delegation packets relayed as user input.
AGENT_RELAYED = re.compile(
    r"^\s*(CHANGES MADE:|EVIDENCE PACKET|#{1,3} (Direct answer|Summary|Result|Findings|Verdict|"
    r"Evidence packet|Status)\b|\*\*(Result|Summary|Findings|Verdict|Status|Evidence)\*\*|"
    r"Direct answer:|Result: \*?\*?(pass|fail|blocked)|Command exited `|Audit complete\.|"
    r"A previous agent produced the plan below|.{0,120} implemented\.\s+No commit created\.|"
    r"▣ DCP \||\d\.\s*TASK:)",
    re.IGNORECASE,
)
PATH_ONLY = re.compile(r"^\s*(~|/)[\w.-]*(/[\w.-]+)+/?\s*$")
TEMPLATES = {
    "codex-review-action": re.compile(
        r"^\s*<user_action>.*?<action>review</action>", re.DOTALL
    ),
    "plan-implement": re.compile(r"^\s*PLEASE IMPLEMENT THIS PLAN", re.IGNORECASE),
    "implement-the-plan": re.compile(r"^\s*Implement the plan\.?\s*$", re.IGNORECASE),
}
PROBE_FIRST = [
    re.compile(pattern, re.IGNORECASE | re.DOTALL)
    for pattern in (
        r"^\s*reply with exactly",
        r"^\s*respond with (only|exactly)",
        r"^\s*say (ok|hi|hello)\s*\.?\s*$",
        r"^\s*(ping|test)\s*\.?\s*$",
    )
]
SECRET = re.compile(
    r"(ghp_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|gho_[A-Za-z0-9]{20,}|sk-[A-Za-z0-9_-]{20,}|"
    r"AKIA[0-9A-Z]{16}|AIza[0-9A-Za-z_-]{30,}|xox[abprs]-[A-Za-z0-9-]{10,}|"
    r"(?i:bearer)\s+[A-Za-z0-9._~+/-]{20,}=*|"
    r"(?i:(?:api[_-]?key|token|secret|password)\s*[=:]\s*)[^\s'\"]{12,})"
)

GITHUB_PR = re.compile(r"https?://github\.com/[\w.-]+/[\w.-]+/pull/\d+", re.IGNORECASE)
REVIEW_WORD = re.compile(r"\breview(s|ed|ing)?\b", re.IGNORECASE)
PR_REVIEW = re.compile(
    r"(\breview\b.*(github\.com/[^\s]+/pull/\d+|\bpr\b|pull request|#\d+))|"
    r"((github\.com/[^\s]+/pull/\d+|\bpr\b|pull request).*\breview\b)",
    re.IGNORECASE | re.DOTALL,
)
REVIEW_COMMAND = re.compile(
    r"^[$/](code-review|github-toolkit|github|review|pr-review|security-review)\b",
    re.IGNORECASE,
)
EXPLICIT_SKILL = re.compile(
    r"(?:^|\s)[$/]([a-z][a-z0-9-]+)(?::([a-z0-9-]+))?\b", re.IGNORECASE
)
STRONG_CORRECTION = re.compile(
    r"^\s*(no|nope|nah|wrong|stop|wait|hold on|actually|hmm+|ugh|why)\b|"
    r"\b(i said|i told you|i asked|i meant|not what i|that'?s not|thats not|you forgot|you missed|you ignored|"
    r"you keep|keep doing|every time|again|still|revert|undo|redo|why did you|why are you|why would you|"
    r"why is (it|this|that)|shouldn'?t|should not|supposed to|we already|i already|come on|wtf|ffs|seriously|"
    r"instead|don'?t|do not|didn'?t|never)\b|!!+",
    re.IGNORECASE,
)
SIGNALS = {
    "stall-nudge": re.compile(
        r"^\s*(sorry,?\s*)?(please\s+)?(continue|keep going|go on|resume|carry on)\b[\s.!]*$|"
        r"\b(are you stuck|you stuck|got stuck|seems stuck|hows it going|how's it going|still working|"
        r"still running|continue if you have next steps|sorry,? (got )?interrupted|sorry,? try again)\b",
        re.IGNORECASE,
    ),
    "bare-commit": re.compile(
        r"^\s*(\$|/)?(please\s+)?(commit(-changes)?|commit (the )?changes|commit and push|commit as you go|"
        r"remember to commit( as you go)?|please commit|commit please)[\s.!]*(please)?[\s.!]*$",
        re.IGNORECASE,
    ),
    "commit-style": re.compile(
        r"\batomic\b.*\bcommits?\b|\bconventional commits?\b|\bcommit as you go\b",
        re.IGNORECASE,
    ),
    "fixup-push": re.compile(r"\b(fixup|autosquash|force[- ]push)\b", re.IGNORECASE),
    "pending-review-ask": re.compile(
        r"\bpending review\b|\bdo not submit\b|\bdon'?t submit\b|review (it )?(from|in) the ui",
        re.IGNORECASE,
    ),
    "verification-ask": re.compile(
        r"\b(did (you|we) (actually )?(test|verify|validate|check|build|confirm)|how confident|are you sure|"
        r"(verified|tested)\?|double check)\b",
        re.IGNORECASE,
    ),
    "model-switch": re.compile(r"^\s*/(model|effort|fast)\b", re.IGNORECASE),
    "plan-implement": re.compile(
        r"^<plan-implement action>$|^\s*implement the plan\.?\s*$", re.IGNORECASE
    ),
}
HARNESS_ERRORS = {
    "gateway-cooldown": "%are cooling down via provider%",
    "usage-limit": "%hit your usage limit%",
    "idle-no-response": "No response requested.%",
    "api-error": "API Error%",
}
LOGLIKE = re.compile(
    r"(error:|warning:|/nix/store/|│|…|\bat «|^\s*(at |>|\$ |\+|-{3,}|={3,}|\d+\|)|"
    r"builder failed|exit code|stack trace|show-trace|for full logs|log lines|^\s*[\[\]{}()<>])",
    re.IGNORECASE,
)
STOP_WORDS = frozenset(
    [
        "a",
        "an",
        "the",
        "and",
        "or",
        "but",
        "if",
        "then",
        "so",
        "to",
        "of",
        "in",
        "on",
        "at",
        "for",
        "with",
        "from",
        "by",
        "as",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "it",
        "its",
        "this",
        "that",
        "these",
        "those",
        "i",
        "me",
        "my",
        "we",
        "our",
        "you",
        "your",
        "can",
        "could",
        "would",
        "should",
        "will",
        "just",
        "please",
        "also",
        "do",
        "does",
        "did",
        "not",
        "no",
        "yes",
        "there",
        "here",
        "what",
        "how",
        "why",
        "when",
        "which",
        "who",
        "all",
        "any",
        "some",
        "more",
        "most",
        "very",
        "really",
        "up",
        "out",
        "about",
        "into",
        "over",
        "than",
        "too",
        "lets",
        "let's",
        "let",
        "us",
        "them",
        "they",
        "he",
        "she",
        "his",
        "her",
        "their",
        "am",
        "have",
        "has",
        "had",
        "get",
        "got",
        "make",
        "made",
        "go",
        "going",
        "want",
        "need",
        "like",
        "one",
        "two",
        "see",
        "look",
        "sure",
        "ok",
        "okay",
        "thanks",
        "thank",
        "hi",
        "hey",
        "still",
    ]
)
EDIT_TOOLS = frozenset(
    {
        "Edit",
        "Write",
        "MultiEdit",
        "NotebookEdit",
        "apply_patch",
        "edit",
        "write",
        "replace_file_content",
        "create_file",
    }
)
PATCH_PATH = re.compile(r"\*\*\* (?:Update|Add) File: ([^\s\\\"]+)")


class HistoryError(Exception):
    """Invalid input or unusable archive."""


# --- Shared helpers --------------------------------------------------------


def connect(path: Path) -> sqlite3.Connection:
    if not path.is_file():
        raise HistoryError(f"archive not found: {path}")
    db = sqlite3.connect(f"{path.resolve().as_uri()}?mode=ro", uri=True)
    db.row_factory = sqlite3.Row
    return db


def table_columns(db: sqlite3.Connection, table: str) -> set[str]:
    return {row[1] for row in db.execute(f"pragma table_info({table})")}


def column(columns: set[str], name: str, fallback: str) -> str:
    return name if name in columns else fallback


def relationship_expression(db: sqlite3.Connection, alias: str = "s") -> str:
    if "relationship_type" in table_columns(db, "sessions"):
        return f"coalesce({alias}.relationship_type,'')"
    return "''"


def installed_pattern(roots: Sequence[str]) -> re.Pattern[str]:
    return re.compile("(?:" + "|".join(roots) + r")/([A-Za-z0-9._-]+)/SKILL\.md")


def explicit_names(text: str, aliases: dict[str, str]) -> Iterable[str]:
    for match in EXPLICIT_SKILL.finditer(text):
        name = (match.group(2) or match.group(1)).lower()
        yield aliases.get(name, name)


def redact(text: str) -> str:
    return SECRET.sub("<redacted-secret>", text)


def day(value: Any) -> str:
    return str(value or "")[:10]


def window_label(value: str, boundaries: Sequence[str]) -> str:
    previous = None
    for boundary in boundaries:
        if value < boundary:
            return f"<{boundary}" if previous is None else f"{previous}..{boundary}"
        previous = boundary
    return f">={previous}" if previous is not None else "all"


def secure_dir(path: Path) -> None:
    path.mkdir(mode=0o700, parents=True, exist_ok=True)
    os.chmod(path, 0o700)


def write_text(path: Path, text: str, force: bool) -> Path:
    if path.exists() and not force:
        raise HistoryError(f"{path} exists; pass --force to replace it")
    secure_dir(path.parent)
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
        handle.write(text)
    os.chmod(path, 0o600)
    return path


def write_json(path: Path, value: Any, force: bool) -> Path:
    return write_text(
        path, json.dumps(value, indent=1, ensure_ascii=False) + "\n", force
    )


def write_jsonl(path: Path, rows: Iterable[dict[str, Any]], force: bool) -> Path:
    return write_text(
        path, "".join(json.dumps(row, ensure_ascii=False) + "\n" for row in rows), force
    )


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.is_file():
        raise HistoryError(f"missing input {path}; run the extract command first")
    with path.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


def markdown_table(headers: Sequence[str], rows: Iterable[Sequence[Any]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    lines.extend(
        "| " + " | ".join(str(cell).replace("|", "\\|") for cell in row) + " |"
        for row in rows
    )
    return "\n".join(lines) + "\n"


# --- status ----------------------------------------------------------------


def status(db: sqlite3.Connection, now: dt.datetime | None = None) -> dict[str, Any]:
    columns = table_columns(db, "sessions")
    relationship = column(columns, "relationship_type", "''")
    rows = db.execute(
        f"""select agent, count(*) sessions, max(started_at) newest,
        sum(case when coalesce({relationship},'')<>'' then 1 else 0 end) subagents
        from sessions group by agent order by sessions desc"""
    ).fetchall()
    agents = [dict(row) for row in rows]
    newest = max((row["newest"] or "" for row in agents), default="")
    now = now or dt.datetime.now(dt.timezone.utc)
    stale_days = None
    if newest:
        parsed = dt.datetime.fromisoformat(newest[:19]).replace(tzinfo=dt.timezone.utc)
        stale_days = round((now - parsed).total_seconds() / 86400, 1)
    return {"agents": agents, "newest_session": newest, "stale_days": stale_days}


# --- extract ---------------------------------------------------------------


def clean(text: str) -> tuple[str | None, dict[str, Any]]:
    meta: dict[str, Any] = {
        "images": 0,
        "slash": None,
        "template": None,
        "dropped": None,
    }
    if not text:
        return None, meta
    raw = text
    for name, pattern in TEMPLATES.items():
        if pattern.search(raw):
            meta["template"] = name
            break
    if meta["template"] == "codex-review-action":
        return "<codex /review action>", meta
    if meta["template"] == "plan-implement":
        # The plan body is agent-authored; keep only the UI action marker.
        return "<plan-implement action>", meta
    command = COMMAND_NAME.search(raw)
    if command:
        arguments = COMMAND_ARGS.search(raw)
        meta["slash"] = command.group(1)
        return (
            f"{command.group(1)} {arguments.group(1).strip() if arguments else ''}".strip(),
            meta,
        )
    meta["images"] = len(re.findall(r"<image name=", raw)) + len(
        IMAGE_TOKEN.findall(raw)
    )
    text = CODEX_REQUEST.sub("", text)
    for block in WRAPPER_BLOCKS:
        text = block.sub("", text)
    text = OPENCODE_MODE.sub("", text)
    text = OPENCODE_INLINED.sub("", text)
    text = IMAGE_TOKEN.sub("", text).strip()
    if not text:
        return ("<image-only>" if meta["images"] else None), meta
    if any(pattern.search(text) for pattern in INJECTED):
        meta["dropped"] = "injected"
        return None, meta
    if AGENT_RELAYED.search(text) or PATH_ONLY.match(text):
        meta["dropped"] = "agent-relayed"
        return None, meta
    if text[0] in "/$":
        meta["slash"] = text.split()[0]
    return text, meta


def prompt_tags(text: str) -> list[str]:
    tags = []
    if GITHUB_PR.search(text):
        tags.append("github_pr_url")
    if PR_REVIEW.search(text):
        tags.append("pr_review")
    if REVIEW_WORD.search(text):
        tags.append("review_any")
    if EXPLICIT_SKILL.search(text):
        tags.append("explicit_skill")
    return tags


def load_sessions(
    db: sqlite3.Connection, agents: Sequence[str]
) -> dict[str, dict[str, Any]]:
    columns = table_columns(db, "sessions")
    fields = {
        "project": column(columns, "project", "''"),
        "cwd": column(columns, "cwd", "''"),
        "entrypoint": column(columns, "entrypoint", "''"),
        "relationship": f"coalesce({column(columns, 'relationship_type', 'NULL')},'')",
        "automated": f"coalesce({column(columns, 'is_automated', '0')},0)",
    }
    select = ", ".join(f"{expression} AS {name}" for name, expression in fields.items())
    placeholders = ",".join("?" * len(agents))
    rows = db.execute(
        f"select id, agent, started_at, {select} from sessions where agent in ({placeholders})",
        list(agents),
    )
    return {row["id"]: dict(row) for row in rows}


def extract(
    db: sqlite3.Connection, agents: Sequence[str], since: str, until: str
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    sessions = {
        sid: sess
        for sid, sess in load_sessions(db, agents).items()
        if since <= day(sess["started_at"]) < until
    }
    columns = table_columns(db, "messages")
    system = column(columns, "is_system", "0")
    timestamp = column(columns, "timestamp", "NULL")
    dropped: collections.Counter[str] = collections.Counter()
    prompts: list[dict[str, Any]] = []
    first_prompt: dict[str, str] = {}
    for row in db.execute(
        f"""select session_id, ordinal, {timestamp} AS ts, content from messages
        where role='user' and coalesce({system},0)=0 order by session_id, ordinal"""
    ):
        sess = sessions.get(row["session_id"])
        if sess is None:
            continue
        if sess["relationship"]:
            dropped["subagent-session"] += 1
            continue
        if sess["automated"]:
            dropped["automated-session"] += 1
            continue
        text, meta = clean(row["content"] or "")
        if text is None:
            dropped[meta["dropped"] or "empty"] += 1
            continue
        first_prompt.setdefault(row["session_id"], text)
        prompts.append(
            {
                "session_id": row["session_id"],
                "agent": sess["agent"],
                "project": sess["project"],
                "session_started": sess["started_at"],
                "ts": row["ts"] or sess["started_at"],
                "ordinal": row["ordinal"],
                "text": redact(text),
                "images": meta["images"],
                "slash": meta["slash"],
                "template": meta["template"],
                "tags": prompt_tags(text),
            }
        )
    probes = {
        sid
        for sid, text in first_prompt.items()
        if any(p.search(text) for p in PROBE_FIRST)
    }
    kept = [prompt for prompt in prompts if prompt["session_id"] not in probes]
    dropped["probe-session"] = len(prompts) - len(kept)
    by_session: dict[str, list[dict[str, Any]]] = collections.defaultdict(list)
    for prompt in kept:
        by_session[prompt["session_id"]].append(prompt)
    for items in by_session.values():
        for index, prompt in enumerate(items):
            prompt["turn"] = index
            prompt["turns_in_session"] = len(items)
    session_rows = [
        {**sessions[sid], "id": sid, "human_turns": len(items)}
        for sid, items in sorted(by_session.items())
    ]
    summary = {
        "sessions": len(by_session),
        "prompts": len(kept),
        "dropped": dict(sorted(dropped.items())),
        "by_agent": dict(collections.Counter(p["agent"] for p in kept).most_common()),
        "by_agent_month": dict(
            sorted(
                collections.Counter(
                    f"{p['agent']} {day(p['ts'])[:7]}" for p in kept
                ).items()
            )
        ),
    }
    return kept, session_rows, summary


# --- threads and digests ---------------------------------------------------


def is_review_session(prompts: Sequence[dict[str, Any]]) -> bool:
    for prompt in prompts:
        tags = set(prompt["tags"])
        if "pr_review" in tags or prompt.get("template") == "codex-review-action":
            return True
        if "github_pr_url" in tags and "review_any" in tags:
            return True
        if (
            prompt.get("slash")
            and REVIEW_COMMAND.match(prompt["slash"])
            and tags & {"github_pr_url", "review_any"}
        ):
            return True
    return False


def build_threads(
    db: sqlite3.Connection,
    prompts: Sequence[dict[str, Any]],
    sessions: Sequence[dict[str, Any]],
    select: str,
    prompt_chars: int,
    reply_chars: int,
) -> list[dict[str, Any]]:
    by_session: dict[str, list[dict[str, Any]]] = collections.defaultdict(list)
    for prompt in prompts:
        by_session[prompt["session_id"]].append(prompt)
    meta = {sess["id"]: sess for sess in sessions}
    skills = observed_skills(db, {}, installed_pattern(DEFAULT_INSTALLED_ROOTS))
    tool_use = column(table_columns(db, "messages"), "has_tool_use", "0")
    records = []
    for sid, items in sorted(by_session.items(), key=lambda kv: kv[1][0]["ts"] or ""):
        if select == "review" and not is_review_session(items):
            continue
        ordinals = [p["ordinal"] for p in items]
        replies = db.execute(
            f"""select ordinal, content, coalesce({tool_use},0) tool from messages
            where session_id=? and role='assistant' order by ordinal""",
            (sid,),
        ).fetchall()
        turns = []
        for index, prompt in enumerate(items):
            end = ordinals[index + 1] if index + 1 < len(ordinals) else float("inf")
            window = [
                r
                for r in replies
                if prompt["ordinal"] < r["ordinal"] < end
                and (r["content"] or "").strip()
            ]
            # Prefer the last prose reply over a trailing tool-call rendering.
            prose = [r for r in window if not r["tool"]] or window
            turns.append(
                {
                    "turn": index,
                    "ts": prompt["ts"],
                    "user": prompt["text"][:prompt_chars],
                    "assistant_final": redact(
                        (prose[-1]["content"] if prose else "")[:reply_chars]
                    ),
                }
            )
        sess = meta.get(sid, {})
        records.append(
            {
                "session_id": sid,
                "agent": items[0]["agent"],
                "project": sess.get("project"),
                "started_at": sess.get("started_at") or items[0]["ts"],
                "skills_loaded": sorted(skills.get(sid, {})),
                "human_turns": len(items),
                "turns": turns,
            }
        )
    return records


def render_chunks(blocks: Iterable[str], chunk_bytes: int) -> list[str]:
    chunks: list[list[str]] = [[]]
    size = 0
    for block in blocks:
        encoded = len(block.encode("utf-8"))
        if size + encoded > chunk_bytes and chunks[-1]:
            chunks.append([])
            size = 0
        chunks[-1].append(block)
        size += encoded
    return ["".join(chunk) for chunk in chunks if chunk]


def digest_blocks(
    threads: Sequence[dict[str, Any]],
    since: str,
    until: str,
    agents: set[str],
    min_turns: int,
    max_turns: int,
    cap_turns: int,
    user_chars: int,
    reply_chars: int,
) -> list[str]:
    blocks = []
    count = 0
    for record in threads:
        started = day(record["started_at"])
        if record["agent"] not in agents or not (since <= started < until):
            continue
        if not (min_turns <= record["human_turns"] <= max_turns):
            continue
        count += 1
        lines = [
            (
                f"\n## S{count} | {record['agent']} | {started} | {record['project']} | "
                f"skills: {','.join(record['skills_loaded']) or '-'} | turns: {record['human_turns']}"
            )
        ]
        for turn in record["turns"][:cap_turns]:
            lines.append(
                f"T{turn['turn']} USER: {' '.join(turn['user'][:user_chars].split())}"
            )
            reply = " ".join(turn["assistant_final"][:reply_chars].split())
            if reply:
                lines.append(f"T{turn['turn']} AGENT: {reply}")
        blocks.append("\n".join(lines) + "\n")
    return blocks


def correction_blocks(
    threads: Sequence[dict[str, Any]],
    review_ids: set[str],
    since: str,
    until: str,
    agents: set[str],
    include_review: bool,
    min_turns: int,
    max_turns: int,
    max_user_chars: int,
    reply_chars: int,
) -> tuple[list[str], int]:
    blocks = []
    selected = 0
    for record in threads:
        started = day(record["started_at"])
        if record["agent"] not in agents or not (since <= started < until):
            continue
        if record["session_id"] in review_ids and not include_review:
            continue
        if not (min_turns <= record["human_turns"] <= max_turns):
            continue
        turns = record["turns"]
        picked = [
            (turn["turn"], turns[index - 1]["assistant_final"], turn["user"])
            for index, turn in enumerate(turns)
            if index > 0
            and len(turn["user"]) <= max_user_chars
            and STRONG_CORRECTION.search(turn["user"])
        ]
        if not picked:
            continue
        first = " ".join(turns[0]["user"][:220].split())
        lines = [
            f"\n## {record['agent']} | {started} | {record['project']} | first: {first}"
        ]
        for number, previous, text in picked:
            lines.append(
                f"  AGENT(prev, tail): {' '.join(previous[-reply_chars:].split())}"
            )
            lines.append(f"  USER T{number}: {' '.join(text.split())}")
        selected += len(picked)
        blocks.append("\n".join(lines) + "\n")
    return blocks, selected


def write_chunks(
    out: Path, prefix: str, chunks: Sequence[str], force: bool
) -> list[str]:
    paths = []
    for index, chunk in enumerate(chunks, 1):
        paths.append(
            str(write_text(out / "digests" / f"{prefix}-{index}.md", chunk, force))
        )
    return paths


# --- routing ---------------------------------------------------------------


def load_triggers(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise HistoryError(f"invalid triggers file {path}: {error}") from error
    skills = data.get("skills")
    if not isinstance(skills, dict) or not skills:
        raise HistoryError(f"triggers file {path} needs a non-empty skills object")
    for name, spec in skills.items():
        if not isinstance(spec, dict) or not isinstance(spec.get("prompt"), str):
            raise HistoryError(f"trigger {name} needs a prompt regex")
        spec["compiled"] = re.compile(spec["prompt"], re.IGNORECASE)
    data.setdefault("aliases", {})
    data["installed"] = installed_pattern(
        data.get("installed_skill_roots") or DEFAULT_INSTALLED_ROOTS
    )
    return data


def skill_created(skills_root: Path | None, name: str) -> str | None:
    if skills_root is None:
        return None
    result = subprocess.run(
        [
            "git",
            "-C",
            str(skills_root),
            "log",
            "--diff-filter=A",
            "--format=%ad",
            "--date=short",
            "--",
            f"{name}/SKILL.md",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    dates = result.stdout.split()
    return dates[-1] if result.returncode == 0 and dates else None


def creation_dates(
    triggers: dict[str, Any], skills_root: Path | None
) -> dict[str, str | None]:
    """Earliest creation date per skill, counting renamed predecessors."""
    created: dict[str, str | None] = {}
    for name, spec in triggers["skills"].items():
        names = [
            name,
            *(old for old, new in triggers["aliases"].items() if new == name),
        ]
        dates = (
            [spec.get("since")]
            if spec.get("since")
            else [skill_created(skills_root, item) for item in names]
        )
        known = [value for value in dates if value]
        created[name] = min(known) if known else None
    return created


def observed_skills(
    db: sqlite3.Connection,
    aliases: dict[str, str],
    installed: re.Pattern[str] | None = None,
) -> dict[str, dict[str, float]]:
    """Map session -> skill -> earliest order key of load evidence."""
    columns = table_columns(db, "tool_calls")
    order = "m.ordinal" if "message_id" in columns else "t.rowid"
    join = (
        "left join messages m on m.id = t.message_id" if "message_id" in columns else ""
    )
    loads: dict[str, dict[str, float]] = collections.defaultdict(dict)

    def note(sid: str, name: str, key: Any) -> None:
        name = aliases.get(name, name)
        position = float(key) if key is not None else float("inf")
        if position < loads[sid].get(name, float("inf")):
            loads[sid][name] = position

    for row in db.execute(
        f"select t.session_id sid, t.skill_name name, {order} pos from tool_calls t {join} "
        "where coalesce(t.skill_name,'')<>''"
    ):
        note(row["sid"], row["name"], row["pos"])
    if installed is not None:
        # AgentsView's skill_name misses most Codex skill reads; count reads of
        # installed copies, not repository sources being edited.
        for row in db.execute(
            f"select t.session_id sid, t.input_json inp, {order} pos from tool_calls t {join} "
            "where t.input_json like '%SKILL.md%'"
        ):
            for name in installed.findall(row["inp"] or ""):
                note(row["sid"], name, row["pos"])
    return loads


def routing(
    db: sqlite3.Connection,
    prompts: Sequence[dict[str, Any]],
    triggers: dict[str, Any],
    boundaries: Sequence[str],
    skills_root: Path | None,
) -> dict[str, Any]:
    aliases = triggers["aliases"]
    loads = observed_skills(db, aliases, triggers["installed"])
    created = creation_dates(triggers, skills_root)
    sessions: dict[str, dict[str, Any]] = {}
    for prompt in prompts:
        # Windows follow the session start, matching extract's date filter.
        started = day(prompt.get("session_started") or prompt["ts"])
        sess = sessions.setdefault(
            prompt["session_id"],
            {
                "agent": prompt["agent"],
                "day": started,
                "expected": set(),
                "explicit": {},
            },
        )
        for name, spec in triggers["skills"].items():
            if spec["compiled"].search(prompt["text"]):
                sess["expected"].add(name)
        for name in explicit_names(prompt["text"], aliases):
            sess["explicit"].setdefault(name, prompt["ordinal"])
    table: dict[tuple[str, str, str], collections.Counter[str]] = (
        collections.defaultdict(collections.Counter)
    )
    for sid, sess in sessions.items():
        for name in sess["expected"]:
            if created.get(name) and sess["day"] < created[name]:
                continue
            counter = table[
                (sess["agent"], name, window_label(sess["day"], boundaries))
            ]
            explicit = name in sess["explicit"]
            loaded = name in loads.get(sid, {})
            counter["expected"] += 1
            counter["explicit"] += int(explicit)
            counter["auto"] += int(loaded and not explicit)
            counter["missing"] += int(not loaded and not explicit)
    rows = [
        {"agent": agent, "skill": skill, "window": window, **dict(counter)}
        for (agent, skill, window), counter in sorted(table.items())
    ]
    return {
        "created": created,
        "rows": rows,
        "edits": edit_before_load(db, prompts, triggers, loads, boundaries),
    }


def edit_before_load(
    db: sqlite3.Connection,
    prompts: Sequence[dict[str, Any]],
    triggers: dict[str, Any],
    loads: dict[str, dict[str, float]],
    boundaries: Sequence[str],
) -> list[dict[str, Any]]:
    suffixes = {
        name: tuple(spec["edit_suffixes"])
        for name, spec in triggers["skills"].items()
        if spec.get("edit_suffixes")
    }
    if not suffixes:
        return []
    columns = table_columns(db, "tool_calls")
    order = "m.ordinal" if "message_id" in columns else "t.rowid"
    join = (
        "left join messages m on m.id = t.message_id" if "message_id" in columns else ""
    )
    # sessions also has file_path; qualify it for the join.
    file_path = "t.file_path" if "file_path" in columns else "NULL"
    relationship = relationship_expression(db)
    explicit: dict[str, dict[str, float]] = collections.defaultdict(dict)
    for prompt in prompts:
        for name in explicit_names(prompt["text"], triggers["aliases"]):
            explicit[prompt["session_id"]].setdefault(name, float(prompt["ordinal"]))
    first_edit: dict[tuple[str, str], tuple[float, str, str, str]] = {}
    tools = ",".join("?" * len(EDIT_TOOLS))
    for row in db.execute(
        f"""select t.session_id sid, t.tool_name tool, {file_path} path, t.input_json inp, {order} pos,
        s.agent agent, s.started_at started, {relationship} rel
        from tool_calls t {join} join sessions s on s.id = t.session_id
        where t.tool_name in ({tools})""",
        sorted(EDIT_TOOLS),
    ):
        paths = [row["path"]] if row["path"] else PATCH_PATH.findall(row["inp"] or "")
        for name, endings in suffixes.items():
            if any(path.endswith(endings) for path in paths if path):
                key = (row["sid"], name)
                position = float(row["pos"]) if row["pos"] is not None else float("inf")
                if key not in first_edit or position < first_edit[key][0]:
                    first_edit[key] = (
                        position,
                        row["agent"],
                        day(row["started"]),
                        "subagent" if row["rel"] else "root",
                    )
    table: dict[tuple[str, str, str, str], collections.Counter[str]] = (
        collections.defaultdict(collections.Counter)
    )
    for (sid, name), (position, agent, started, kind) in first_edit.items():
        loaded_at = min(
            loads.get(sid, {}).get(name, float("inf")),
            explicit.get(sid, {}).get(name, float("inf")),
        )
        outcome = (
            "before-edit"
            if loaded_at <= position
            else ("after-edit" if loaded_at < float("inf") else "never")
        )
        table[(agent, kind, name, window_label(started, boundaries))][outcome] += 1
    return [
        {
            "agent": agent,
            "session_kind": kind,
            "skill": name,
            "window": window,
            **dict(counter),
        }
        for (agent, kind, name, window), counter in sorted(table.items())
    ]


def routing_markdown(report: dict[str, Any]) -> str:
    rows = []
    for row in report["rows"]:
        expected = row.get("expected", 0)
        rows.append(
            (
                row["agent"],
                row["skill"],
                row["window"],
                expected,
                f"{100 * row.get('auto', 0) / expected:.0f}%" if expected else "-",
                f"{100 * row.get('explicit', 0) / expected:.0f}%" if expected else "-",
                f"{100 * row.get('missing', 0) / expected:.0f}%" if expected else "-",
            )
        )
    text = "# Skill routing\n\nKeyword-triggered sessions; windows split on the supplied boundaries.\n\n"
    text += markdown_table(
        ("agent", "skill", "window", "sessions", "auto", "explicit", "missing"), rows
    )
    if report["edits"]:
        text += "\n## Skill loaded before first matching edit\n\n"
        text += markdown_table(
            ("agent", "kind", "skill", "window", "before-edit", "after-edit", "never"),
            (
                (
                    r["agent"],
                    r["session_kind"],
                    r["skill"],
                    r["window"],
                    r.get("before-edit", 0),
                    r.get("after-edit", 0),
                    r.get("never", 0),
                )
                for r in report["edits"]
            ),
        )
    return text


# --- phrases ---------------------------------------------------------------


def prose_tokens(text: str) -> list[str]:
    kept = []
    for line in text.splitlines():
        letters = sum(ch.isalpha() or ch.isspace() for ch in line)
        if line.strip() and not LOGLIKE.search(line) and letters >= 0.8 * len(line):
            kept.append(line)
    lowered = "\n".join(kept).lower()
    lowered = re.sub(r"https?://\S+", " <url> ", lowered)
    lowered = re.sub(r"(?:~|/)[\w./-]{3,}", " <path> ", lowered)
    lowered = re.sub(r"\b\d+\b", " <n> ", lowered)
    return re.findall(r"<url>|<path>|<n>|[a-z$][a-z0-9'$_-]*", lowered)


def phrases(
    prompts: Sequence[dict[str, Any]], min_sessions: int, limit: int
) -> dict[str, Any]:
    grams: dict[tuple[str, ...], set[str]] = collections.defaultdict(set)
    months: dict[tuple[str, ...], set[str]] = collections.defaultdict(set)
    short: dict[str, set[str]] = collections.defaultdict(set)
    for prompt in prompts:
        if prompt.get("template"):
            continue
        tokens = prose_tokens(prompt["text"][:4000])
        normalized = " ".join(tokens)
        if 0 < len(normalized) <= 60:
            short[normalized].add(prompt["session_id"])
        seen = set()
        for size in range(3, 8):
            for start in range(len(tokens) - size + 1):
                gram = tuple(tokens[start : start + size])
                content = [
                    token
                    for token in gram
                    if token not in STOP_WORDS and not token.startswith("<")
                ]
                if len(content) < 2 or gram in seen:
                    continue
                seen.add(gram)
                grams[gram].add(prompt["session_id"])
                months[gram].add(day(prompt["ts"])[:7])
    ranked = sorted(
        ((gram, len(ids)) for gram, ids in grams.items() if len(ids) >= min_sessions),
        key=lambda item: (-len(item[0]), -item[1]),
    )
    kept: list[tuple[tuple[str, ...], int]] = []
    for gram, count in ranked:
        text = " ".join(gram)
        # Keep maximal phrases: drop a gram covered by a longer one with similar reach.
        if any(
            text in " ".join(longer) and longer_count >= 0.85 * count
            for longer, longer_count in kept
        ):
            continue
        kept.append((gram, count))
    kept.sort(key=lambda item: -item[1])
    return {
        "phrases": [
            {
                "phrase": " ".join(gram),
                "sessions": count,
                "months": sorted(months[gram]),
            }
            for gram, count in kept[:limit]
        ],
        "short_prompts": [
            {"prompt": text, "sessions": len(ids)}
            for text, ids in sorted(short.items(), key=lambda item: -len(item[1]))[
                :limit
            ]
            if len(ids) >= min_sessions
        ],
    }


def phrases_markdown(report: dict[str, Any]) -> str:
    text = "# Repeated phrases\n\nPhrases typed in many separate sessions.\n\n"
    text += markdown_table(
        ("sessions", "phrase", "first", "last"),
        (
            (p["sessions"], p["phrase"], p["months"][0], p["months"][-1])
            for p in report["phrases"]
        ),
    )
    text += "\n## Repeated short prompts\n\n"
    text += markdown_table(
        ("sessions", "prompt"),
        ((p["sessions"], p["prompt"]) for p in report["short_prompts"]),
    )
    return text


# --- signals ---------------------------------------------------------------


def signals(
    db: sqlite3.Connection, prompts: Sequence[dict[str, Any]], boundaries: Sequence[str]
) -> dict[str, Any]:
    windows: dict[tuple[str, str], collections.Counter[str]] = collections.defaultdict(
        collections.Counter
    )
    sessions: dict[tuple[str, str], set[str]] = collections.defaultdict(set)
    for prompt in prompts:
        key = (prompt["agent"], window_label(day(prompt["ts"]), boundaries))
        sessions[key].add(prompt["session_id"])
        windows[key]["prompts"] += 1
        for name, pattern in SIGNALS.items():
            if pattern.search(prompt["text"]):
                windows[key][name] += 1
    message_columns = table_columns(db, "messages")
    relationship = relationship_expression(db)
    stamp = "m.timestamp" if "timestamp" in message_columns else "s.started_at"
    subtype = "m.source_subtype" if "source_subtype" in message_columns else "NULL"
    errors: dict[tuple[str, str, str], collections.Counter[str]] = (
        collections.defaultdict(collections.Counter)
    )
    for name, pattern in HARNESS_ERRORS.items():
        for row in db.execute(
            f"""select s.agent agent, substr(coalesce({stamp}, s.started_at),1,7) month,
            {relationship} rel, count(*) n from messages m join sessions s on s.id = m.session_id
            where m.role='assistant' and m.content like ? group by 1,2,3""",
            (pattern,),
        ):
            errors[(row["agent"], row["month"], "subagent" if row["rel"] else "root")][
                name
            ] += row["n"]
    interrupts = collections.Counter()
    for row in db.execute(
        f"""select s.agent agent, substr(coalesce({stamp}, s.started_at),1,7) month, count(*) n
        from messages m join sessions s on s.id = m.session_id
        where m.role='user' and {relationship}='' and (m.content like '[Request interrupted by user%'
        or {subtype}='interrupted') group by 1,2"""
    ):
        interrupts[(row["agent"], row["month"])] = row["n"]
    return {
        "prompt_signals": [
            {
                "agent": agent,
                "window": window,
                "sessions": len(sessions[(agent, window)]),
                **dict(counter),
            }
            for (agent, window), counter in sorted(windows.items())
        ],
        "harness_errors": [
            {"agent": agent, "month": month, "session_kind": kind, **dict(counter)}
            for (agent, month, kind), counter in sorted(errors.items())
        ],
        "interrupts": [
            {"agent": agent, "month": month, "count": count}
            for (agent, month), count in sorted(interrupts.items())
        ],
    }


def signals_markdown(report: dict[str, Any]) -> str:
    names = list(SIGNALS)
    rows = []
    for row in report["prompt_signals"]:
        prompts = row.get("prompts", 0) or 1
        rows.append(
            (
                row["agent"],
                row["window"],
                row["sessions"],
                row.get("prompts", 0),
                *(f"{100 * row.get(n, 0) / prompts:.1f}" for n in names),
            )
        )
    text = "# Harness signals\n\nPrompt signals per 100 prompts.\n\n"
    text += markdown_table(("agent", "window", "sessions", "prompts", *names), rows)
    text += "\n## Harness errors in assistant messages\n\n"
    error_names = list(HARNESS_ERRORS)
    text += markdown_table(
        ("agent", "month", "kind", *error_names),
        (
            (
                r["agent"],
                r["month"],
                r["session_kind"],
                *(r.get(n, 0) for n in error_names),
            )
            for r in report["harness_errors"]
        ),
    )
    return text


# --- ledger ----------------------------------------------------------------


def blame_lines(file: Path, repo: Path) -> list[tuple[str, str]]:
    try:
        relative = file.resolve().relative_to(repo)
    except ValueError as error:
        raise HistoryError(
            f"{file} resolves outside {repo}; pass the repository source file"
        ) from error
    result = subprocess.run(
        ["git", "-C", str(repo), "blame", "--line-porcelain", "--", str(relative)],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise HistoryError(f"git blame failed for {file}: {result.stderr.strip()}")
    lines: list[tuple[str, str]] = []
    sha = ""
    for line in result.stdout.splitlines():
        if line.startswith("\t"):
            lines.append((sha, line[1:]))
        elif re.match(r"^[0-9a-f]{40} ", line):
            sha = line.split()[0]
    return lines


def commit_info(repo: Path, shas: Iterable[str]) -> dict[str, dict[str, str]]:
    real = sorted({sha for sha in shas if sha.strip("0")})
    info: dict[str, dict[str, str]] = {}
    if real:
        result = subprocess.run(
            [
                "git",
                "-C",
                str(repo),
                "show",
                "-s",
                "--date=short",
                "--format=%H%x1f%ad%x1f%s%x1f%b%x1e",
                *real,
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            raise HistoryError(f"git show failed: {result.stderr.strip()}")
        for record in result.stdout.split("\x1e"):
            parts = record.strip("\n").split("\x1f")
            if len(parts) == 4:
                why = next(
                    (line.strip() for line in parts[3].splitlines() if line.strip()), ""
                )
                info[parts[0]] = {"date": parts[1], "subject": parts[2], "why": why}
    return info


def rule_blocks(lines: Sequence[tuple[str, str]]) -> list[dict[str, Any]]:
    blocks: list[dict[str, Any]] = []
    current: dict[str, Any] | None = None
    fenced = False
    for number, (sha, text) in enumerate(lines, 1):
        stripped = text.strip()
        if not stripped and not fenced:
            current = None
            continue
        # Headings and list items open blocks; other lines continue one.
        starts = not fenced and bool(
            stripped.startswith("#") or re.match(r"^([-*]|\d+\.)\s", text)
        )
        if current is None or starts:
            current = {"start": number, "end": number, "lines": [], "shas": []}
            blocks.append(current)
        current["end"] = number
        current["lines"].append(text)
        current["shas"].append(sha)
        if stripped.startswith("```"):
            fenced = not fenced
        if stripped.startswith("#") and not fenced:
            current = None
    return blocks


def ledger(file: Path, repo: Path | None) -> dict[str, Any]:
    if not file.is_file():
        raise HistoryError(f"instruction file not found: {file}")
    if repo is None:
        top = subprocess.run(
            ["git", "-C", str(file.resolve().parent), "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=False,
        )
        if top.returncode != 0:
            raise HistoryError(f"{file} is not inside a git repository")
        repo = Path(top.stdout.strip())
    lines = blame_lines(file, repo.resolve())
    info = commit_info(repo, (sha for sha, _ in lines))
    result = []
    for block in rule_blocks(lines):
        commits = []
        for sha in dict.fromkeys(block["shas"]):
            meta = info.get(sha)
            commits.append(
                {"sha": sha[:9], **meta}
                if meta
                else {"sha": "uncommitted", "date": "", "subject": "", "why": ""}
            )
        commits.sort(key=lambda item: item["date"])
        dated = [item["date"] for item in commits if item["date"]]
        result.append(
            {
                "lines": f"{block['start']}-{block['end']}",
                "text": " ".join(" ".join(block["lines"]).split())[:160],
                "first_added": min(dated) if dated else "",
                "last_changed": max(dated) if dated else "",
                "commits": commits,
            }
        )
    return {"file": str(file), "blocks": result}


def ledger_markdown(report: dict[str, Any]) -> str:
    text = f"# Rule ledger: {report['file']}\n\n"
    return text + markdown_table(
        ("lines", "added", "changed", "latest commit", "text"),
        (
            (
                block["lines"],
                block["first_added"],
                block["last_changed"],
                (block["commits"][-1]["sha"] + " " + block["commits"][-1]["subject"])
                if block["commits"]
                else "",
                block["text"],
            )
            for block in report["blocks"]
        ),
    )


# --- CLI -------------------------------------------------------------------


def add_scope(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--since", default="", help="first session date to include (YYYY-MM-DD)"
    )
    parser.add_argument(
        "--until",
        default="9999-12-31",
        help="first session date to exclude (YYYY-MM-DD)",
    )
    parser.add_argument(
        "--agents",
        default=",".join(DEFAULT_AGENTS),
        help="comma-separated archive agents",
    )


def add_output(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--out", type=Path, required=True, help="run directory for derived artifacts"
    )
    parser.add_argument(
        "--force", action="store_true", help="replace existing artifacts"
    )


def add_boundaries(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--boundary",
        action="append",
        default=[],
        help="policy change date splitting comparison windows; repeatable",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=DESCRIPTION)
    sub = parser.add_subparsers(dest="command", required=True)
    for name, text in (
        ("status", "report archive coverage and staleness"),
        ("extract", "write cleaned human prompts and session metadata"),
        ("threads", "write turn-level transcripts from extracted prompts"),
        ("digest", "render review threads as chunked worker digests"),
        ("corrections", "render follow-up correction turns as chunked digests"),
        ("routing", "compare expected and observed skill loads"),
        ("phrases", "rank phrases repeated across sessions"),
        ("signals", "count stall, commit, review, and harness-error signals"),
        ("ledger", "trace git provenance for each rule block in an instruction file"),
        ("run", "run status, extract, threads, routing, phrases, signals, and digests"),
    ):
        child = sub.add_parser(name, help=text)
        if name != "ledger":
            child.add_argument(
                "--db", type=Path, default=DEFAULT_DB, help="AgentsView sessions.db"
            )
        if name in {"extract", "run", "digest", "corrections"}:
            add_scope(child)
        if name != "status":
            add_output(child)
        if name in {"routing", "signals", "run"}:
            add_boundaries(child)
        if name in {"routing", "run"}:
            child.add_argument("--triggers", type=Path, default=DEFAULT_TRIGGERS)
            child.add_argument(
                "--skills-root",
                type=Path,
                help="git checkout of canonical skills for creation dates",
            )
        if name in {"threads", "run"}:
            child.add_argument("--prompt-chars", type=int, default=1600)
            child.add_argument("--reply-chars", type=int, default=1200)
        if name in {"digest", "corrections", "run"}:
            child.add_argument("--chunk-bytes", type=int, default=420_000)
            child.add_argument("--min-session-turns", type=int, default=2)
            child.add_argument("--max-session-turns", type=int, default=45)
        if name == "digest":
            child.add_argument("--threads", default="threads-review.jsonl")
            child.add_argument("--prefix", default="review")
            child.add_argument("--cap-turns", type=int, default=45)
        if name == "corrections":
            child.add_argument("--prefix", default="corrections")
            child.add_argument("--include-review", action="store_true")
        if name == "phrases":
            child.add_argument("--min-sessions", type=int, default=6)
            child.add_argument("--limit", type=int, default=150)
        if name == "ledger":
            child.add_argument(
                "--file",
                type=Path,
                required=True,
                help="instruction file, such as base.md",
            )
            child.add_argument(
                "--repo",
                type=Path,
                help="git repository root; defaults to the file's repository",
            )
    return parser


def run_threads(args: argparse.Namespace, db: sqlite3.Connection) -> dict[str, Any]:
    prompts = read_jsonl(args.out / "prompts.jsonl")
    sessions = read_jsonl(args.out / "sessions.jsonl")
    review = build_threads(
        db, prompts, sessions, "review", args.prompt_chars, args.reply_chars
    )
    everything = build_threads(
        db, prompts, sessions, "all", args.prompt_chars, args.reply_chars
    )
    write_jsonl(args.out / "threads-review.jsonl", review, args.force)
    write_jsonl(args.out / "threads-all.jsonl", everything, args.force)
    return {"review_sessions": len(review), "sessions": len(everything)}


def run_digests(
    args: argparse.Namespace, threads_name: str, prefix: str, cap_turns: int
) -> list[str]:
    threads = read_jsonl(args.out / threads_name)
    blocks = digest_blocks(
        threads,
        args.since,
        args.until,
        set(args.agents.split(",")),
        args.min_session_turns,
        args.max_session_turns,
        cap_turns,
        1200,
        700,
    )
    return write_chunks(
        args.out, prefix, render_chunks(blocks, args.chunk_bytes), args.force
    )


def run_corrections(
    args: argparse.Namespace,
    prefix: str,
    include_review: bool,
    min_turns: int,
    max_turns: int,
    reply_chars: int,
) -> dict[str, Any]:
    threads = read_jsonl(args.out / "threads-all.jsonl")
    review_ids = {
        row["session_id"] for row in read_jsonl(args.out / "threads-review.jsonl")
    }
    blocks, selected = correction_blocks(
        threads,
        review_ids,
        args.since,
        args.until,
        set(args.agents.split(",")),
        include_review,
        min_turns,
        max_turns,
        1500,
        reply_chars,
    )
    paths = write_chunks(
        args.out, prefix, render_chunks(blocks, args.chunk_bytes), args.force
    )
    return {"turns": selected, "files": paths}


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        if args.command == "ledger":
            report = ledger(args.file, args.repo)
            write_json(args.out / "ledger.json", report, args.force)
            write_text(args.out / "ledger.md", ledger_markdown(report), args.force)
            print(json.dumps({"blocks": len(report["blocks"]), "out": str(args.out)}))
            return 0
        db = connect(args.db)
        if args.command == "status":
            print(json.dumps(status(db), indent=1))
            return 0
        agents = getattr(args, "agents", ",".join(DEFAULT_AGENTS)).split(",")
        boundaries = sorted(getattr(args, "boundary", []) or [])
        manifest: dict[str, Any] = {}
        if args.command in {"extract", "run"}:
            if (
                args.command == "run"
                and args.out.exists()
                and any(args.out.iterdir())
                and not args.force
            ):
                raise HistoryError(
                    f"{args.out} is not empty; pass --force to replace its artifacts"
                )
            prompts, sessions, summary = extract(db, agents, args.since, args.until)
            write_jsonl(args.out / "prompts.jsonl", prompts, args.force)
            write_jsonl(args.out / "sessions.jsonl", sessions, args.force)
            write_json(args.out / "extract-summary.json", summary, args.force)
            manifest["extract"] = summary
        if args.command in {"threads", "run"}:
            manifest["threads"] = run_threads(args, db)
        if args.command in {"routing", "run"}:
            report = routing(
                db,
                read_jsonl(args.out / "prompts.jsonl"),
                load_triggers(args.triggers),
                boundaries,
                args.skills_root,
            )
            write_json(args.out / "routing.json", report, args.force)
            write_text(args.out / "routing.md", routing_markdown(report), args.force)
            manifest["routing_rows"] = len(report["rows"])
        if args.command in {"phrases", "run"}:
            report = phrases(
                read_jsonl(args.out / "prompts.jsonl"),
                getattr(args, "min_sessions", 6),
                getattr(args, "limit", 150),
            )
            write_json(args.out / "phrases.json", report, args.force)
            write_text(args.out / "phrases.md", phrases_markdown(report), args.force)
            manifest["phrases"] = len(report["phrases"])
        if args.command in {"signals", "run"}:
            report = signals(db, read_jsonl(args.out / "prompts.jsonl"), boundaries)
            write_json(args.out / "signals.json", report, args.force)
            write_text(args.out / "signals.md", signals_markdown(report), args.force)
            manifest["signals_rows"] = len(report["prompt_signals"])
        if args.command == "digest":
            manifest["digests"] = run_digests(
                args, args.threads, args.prefix, args.cap_turns
            )
        if args.command == "corrections":
            manifest["corrections"] = run_corrections(
                args,
                args.prefix,
                args.include_review,
                args.min_session_turns,
                args.max_session_turns,
                450,
            )
        if args.command == "run":
            manifest["status"] = status(db)
            manifest["review_digests"] = run_digests(
                args, "threads-review.jsonl", "review", 45
            )
            manifest["correction_digests"] = run_corrections(
                args,
                "corrections",
                False,
                args.min_session_turns,
                args.max_session_turns,
                450,
            )
            manifest["orchestration_digests"] = run_corrections(
                args, "orchestration", True, args.max_session_turns + 1, 10**9, 350
            )
            manifest["arguments"] = {
                "since": args.since,
                "until": args.until,
                "agents": agents,
                "boundaries": boundaries,
            }
            write_json(args.out / "manifest.json", manifest, args.force)
        print(json.dumps(manifest, indent=1, default=str)[:4000])
        return 0
    except HistoryError as error:
        print(f"history_audit: {error}", file=sys.stderr)
        return 2
    except (sqlite3.Error, OSError) as error:
        print(f"history_audit: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
