OPENAI_SECURA_KEY: ENC[AES256_GCM,data:jbYNZviCVsqafr14R2hDpDlvH9hLhD2UNhSEt3lG+KKmqXqNYHdE8R3R+1X+7dDpFk3C/6fdpHM8F+dKDyaapfTpY3RiBj6i+B1zNrwl2GTvjGz8CxrftvrIDI29igEGONRQGT8rbTsdEfY22e7AcFN7bXo6KUbV6kg0ED+NcJWpdQkoDO5e9p82GjMRHLpXbcVB2AjhowEr1gHxdBDEjk5PshQ=,iv:GJV74uxJbXeARLKAoHSfgpqxpeLuRLOrkxRoWIu7Hj0=,tag:hiDTPZRxjP/zOaB9NMedUw==,type:str]
sops:
  age:
    - recipient: age1547vqtqhgtxu54eewxwttjsfd85w0lm4f46fyxxhnx2ydxt7kyxs36ts2d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMjJ2czQvWlh5TVByMmtZ
        eGVGMW91QW5HekR0aTRsS3NNZk9CL0ljNHpJCmRWRkZJWCt0bUxsUXA2VkpYT1Rq
        QUhTWVFyRWw5aU1KZkVZNldmaXpDM3MKLS0tIHFnN1R3ZVhyNDZWTXE4QlpORUE1
        K2d0KzYwTmJwUEljQjc1UjY2dkJIYkkKSwmgNjJTXK/wlYIxTRB18DxhN7Lnakmd
        MN/sAFbhPHqlp3uqRDWrkEacDNFpnpBMkrkEponCBPHNJ8/bW0NaJg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1xxpd2a56xjj9kzx7xt2ax6w36a68vtzcd8enrnvup6m6wfr6upwq8fr5h5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRGt3aVVwRFlpNEk0NTRZ
        Q2dLZUMwbnBuanZRWkJiYi9tYjg3MTBQZTBnCmhTY0kwS2hGelY5NjFDbU1oVDJ0
        VkYxRFVIUmxtdDBFRXU5SmJReTBCd2cKLS0tIEU5ZC9UbitWYmFjSUZVWWdzQU1a
        SXhJS2xiaWVvVnVxMUxSSVk4QW9BMGcKHK06WyxwHGzjPEKeQREMLhXwqKKxYvb0
        aEWbhrMEw2Jmc/GZh/zOkzzeatY0VVgPzG/W8hOFOZDCaTUCtGzBdA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age13xfa77f49ne56z3yyqh9qc9upjmrjfva8kcvg3jfem2m99dhr9fs34gdrp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QVNHd25FMzh1dEdlbjdW
        NjdGSGZQeHVVL1pBNkZ1dCtQT2ZadEYraGk4CitaRFZFUVhVWDRqZHZDNy9LTnFE
        KzdoZnJRZTRFa2lnc2pBRm5ld2g5MTgKLS0tIEszTkdWRnhFMEQ1b3czTnB1UkJD
        LzNaTXJwUkl6MnpVZ2NaYmhmWm1WOTgKmEa4s5lBG8uoOhf5W4KSUoU1+xMZ+vF7
        alMjY3gjfn4W9pM4WjkGgLkCDaEAyfMrjcf1+Zf64etQ1IiHV/xOaw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1q2qaahrx4chvsa5g7xqwrwk28mld6kn4md8crcrqg046m8yt2efsugl8vr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpK3UzWEFtY2Y3YS9FdkUw
        RWtTQkxuZGh2cmZVYnpoeEg2eERwUHV1QWlnClJWK0hnNm5FVWkrMmI0Y2pLWmFn
        VFAyVENTT1lRdzJVZUIxZ0IyS1FMWlkKLS0tIE5DWFp2QU1uZmczU3hoSmxvWlg4
        T0U0dnZ6REgvVzNGZXRPeVlidDVxS3cK02mU67/iyodqN3Sgs+rtz0ZCep9PZkm5
        ujO/Tod56E7AyQ2PCMIW2RNa7M+jWQPFmMddQurBY+zHcGttfRw86w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1r6tnk84tdmrf58rmppqprv8lyl7turnqsgtg8z6uq48pegwrqqwq0ke8e0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a0RPTjQ5bzhTS2FOenJX
        QVNQN2QvekZwMnVyU3p5N1l0b0Q5dFV1c3owCk9pWVlucWdBUXJQc1pQSEdiNlVE
        d2tiN284bnJjN3IyanA5eGZYYUp6NEUKLS0tIEJXOXc1QjczcXpVcHMxb0FQZVpQ
        NzVQVDR4aTYrdFd3WDVsSGFkRTh6Um8Kef2k6pV+QRtLc6FMBwCUP+8790hgJVUI
        QfV1eaO+VG9Ce5JGSZfWFZve6zPTFT5u+gLrAsV2RIZksIQ3neO/UA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1j6dyfn0dwusaaxmwf49smvc5akp3nv6jla5jv65uph9hgg0kc9sskvrc26
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiU0NHS2prYy9ST0JHUUp4
        amo3cENSWldYVWJLSmdEOUMrNlpUT1paV1Y4CjdENWdJZGQrNEUzQ1Vub3ZVMTEx
        SmVzTFN4M0RGeHp4bmZHZ3plN1lWZVUKLS0tIGZwclZRMEc5Wk1IUnNmSDdad08y
        UVhnL0c4UmQzUjYzTktiNENoMUZBQmsKPZDXLgNkB5IOC1UoEKOCFBHHgUdHIZQh
        aSk+hR9/2Njjb51tlp2xv/GZhrBCUQFxM746oIpiSbXwaPzVG7a6Ew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T18:58:03Z"
  mac: ENC[AES256_GCM,data:7qkQDlMDUR9oHLRyVFO258Vg6jxYsNL5InR3wR+GP2X7xcN9zwPgw4n8H0Gjr2UivmpPx978LqnxWRo5ICwDHZa1uY5jhKh4dhlMAz8ZkmMQBWM3UjyCySBxnXquFfOoJ+zE4qIMsxCjiG9kvxDzGfoSzbtsb40l0ixIJKcjbYs=,iv:kcr/4+IBhzPCTnV3UGZxVwx8NzklArzOi9VfVlzKFUk=,tag:0XW5vhxXSJ0HEewyuzV4Mw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.0
