#!/usr/bin/env lua

Sbar = require("sketchybar")
Sbar.begin_config()
dofile((os.getenv("HOME") or "") .. "/.config/dynamic-island-sketchybar/init.lua")
Sbar.hotload(true)
Sbar.end_config()
Sbar.event_loop()
