cloudflared_json: ENC[AES256_GCM,data:1XBjdxaX9Pbb8jgVo7iLJLxvGuDEfHIN57arSg+bRKN7hpVI9nHn7QwqVEI9o/WvTPgeFYRPfwPxhb7+40dcRU+tguaA4O5HNxu13XaEwLlE2uBLAX5rio6kHafSlz67a2jdnoaXl2ERmMMqAX4Qu5O2sAvmk821H5tcUH+Q2aiXz3pawY3qubduc81vdF410P0qAmQVOs2fWMceC5RvSLja,iv:TerdHeWHs/1OoAtZdi+M04X94sX50TPM8KxC4xTnxxI=,tag:VkHc/HrWF1eBATI/4AgllA==,type:str]
cloudflared_service: ENC[AES256_GCM,data:snDaI+USNTLkIoEPlRPxJCmSVnDvGnQ5FA==,iv:VydDIjijAjo0RAbN/XoO75asf6SGcQ1zR2EVPRLRK5c=,tag:Oi7qP4KY6twGVuH++MA0qA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1547vqtqhgtxu54eewxwttjsfd85w0lm4f46fyxxhnx2ydxt7kyxs36ts2d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dDYxMFhaS0dHZ2ZKelUy
        WTBqQ3UvRENvSGM3R0czcm9zTnpkd2pWWVJ3Ci94MnIwYlNHM3dKR0kxeDU5ZUtw
        NHEwZSt1bFo4TEpTT3dOTXNBczJGeGMKLS0tIGhlNlBwUEVEM3hsMzZnaVBmTmR5
        RW9oSVlOR2x1Zkk5TVl3Um80M3hmV2cKMgEXEoBszkJp2iO+TW+UtwhmGC+ASYq4
        rEchzf6U10JTxkhqhVGXSxRvU25jJ/037EkNXX7nGWcZ8OHnS3ccHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-12-11T04:57:48Z"
  mac: ENC[AES256_GCM,data:b1oGHdteiSpQaNNRd1k/9dF0cPKXQ4JPywdsvk3sKSIvy3M3QhXrQ9j2++vDM2Xh7x4UNHGFxiByA71YkCeLG0lVAwjcfKTc4QqVJdS83k79L0juarFejyww2N6mE6/BwYw5oFH3Hk3QJxnaB2/a87iYglNtXGHY19qLDpMMQpk=,iv:XHCyMZJTZ9rEE7DoldhQwEcoff0BPmU56I4orHJ/eak=,tag:w1JgKoEl8cTso650BuZWIg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
