github:
    access-token: ENC[AES256_GCM,data:9+y0aHVlcQNznhZtTXoZG7+i/CbMfN2IsOfFVdTzqg8wKEOLdQOW4edUe4kcsd3+iiwq,iv:+6eFd/X9LGqmf6Sa8ZeifPh1u+q8gfTYkQ89dqGgcS0=,tag:0gBoHqqFuCXS89lpATUw4w==,type:str]
nix: ENC[AES256_GCM,data:9BQWWys1jfiLhAnZsz7frwgSB988PzPcO2b0g3nk2/P5yyBcGQuRONR0uKzKXs2iNquF5ZG56QZgk0vh1cc9Cewl4Q==,iv:p6beydvlmuc8RhMBdJyKXiUfJZmLpC0FPAfTVTm/ZUg=,tag:v/xi4ARU/lIiuE9abIbrRg==,type:str]
slack:
    token: ENC[AES256_GCM,data:Daghmguclia9+iIkiy3so7mGxiYGh1s4sQpScWmgx2qOp+99ECLXu1wV42yJyoCBSqIqYPpYoJCL006LLRGcmnarPknkJ+5s5IqLag==,iv:FkJHhOj6tMMaXfFDHLgngf6BYpF8G8W06RNjtXQsIlA=,tag:kmSMXCzO4bJ31ESw/zjgnw==,type:str]
twitch:
    token: ENC[AES256_GCM,data:HkF4lhkmw7tgv8nC3Q3l/9IbotYUfT8X8mkSB+wULCjc3OB1,iv:89fBsvWES5HXnTRy73EBnSUKzV6lZ3xJletS3RkDxVo=,tag:MHVpiLvo/mGc5adkU6Y0DA==,type:str]
twitch-tui: ENC[AES256_GCM,data:GzNHfM0hsaV7Rj1A9PjNPcUOlwq+v5ESgJx00L7tuJrqI2IXsN+tYjRv/9MVzESDVZoRumD+rkixzjeKGSvTbn/NdxdzrdNLA2HzW+D5Ht/uM/O7XrEp8lxgWW3q5tkYIvAKomBQ6CtHq92azHgGuYSuQY3hust5Ga3BeXKgDFGbDQ==,iv:dhf4lhCpjfWQda/DmsfTvihDwL4ilUzSBj34tTMWgBw=,tag:zZ/uCDK0MbvEJDKxAQHs9w==,type:str]
wakatime: ENC[AES256_GCM,data:nYC15Uc7Uy6b0gCIrSUyOu/DaBCNC7wQYn+OFrFw/nTrCM2hQ92x3cHwJpilRlxMbesRetDAMi3wPQc3SZueBoHgNFKg9HU1o3BdmUuO94QwAJzVXhhuIz05Y6OmwyCB6CgXY4SEYOrwJFQNIBcXhznwtn+2pS7dPEYRVR/OupaAhTCvDjtc/Jik23oiNpDOY8YfKKr8qIKV5wJNtRy9m8WrpUUaoLmFayggcALnwbMyLuo=,iv:ZUg2QNLCDtGSmo4wfWvmG8UnA8r+iSFPoWS5sJstcik=,tag:QZ2lIpw2Y2cOWfz+DXlJ8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1547vqtqhgtxu54eewxwttjsfd85w0lm4f46fyxxhnx2ydxt7kyxs36ts2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb3hpWUVQMEVNRm5XQ0hP
            VVZ4M25NcWVwNVlHcVpkZ2xodk9YZmRrVjFZClRpViszZTZxMFFhMFM1cDZ3cnRD
            ZEhtU01iRjR4WTcrdWE0YkJPNEo2TWMKLS0tIDBaSHRKY1A2clRjSXBydE04RXF2
            ZTNjd2FvbEk5ZkhSMnIxM1BBWllEWTgKXtyEBhmw/s4qOx0uo24+wj/7M3n1g1rw
            YxwXqX7PZuI9ssdHZs6DdB30JoppJG/9d/ml8+KAV2zHmt08mieTyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13xfa77f49ne56z3yyqh9qc9upjmrjfva8kcvg3jfem2m99dhr9fs34gdrp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaGUxVVFOZjZoOFcxeVdB
            Q2t2L3RwZ29VVGtrdG5rdm81WTRYN1NiWUFRCmdnOHlGMzhHdlNYVjhPSzd2MkNB
            bWloWU1Wb3licXNFT2VkYkphTW84bTAKLS0tIDJaRFc4eU91bnlPb25xMTN2V3NL
            Y0JVSmdWVGErOHR5OURaWitkSmR5ZncK8HlxWOyKxPlKWjaJ+CMv527NU9bNlqM0
            C4kOuA8QQU51kc13CidF2CVoFqVaMnPIg5kXfKJptfXQ5QQEPYYgkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qh2epukpmcg69386v5shr3w9l2tvryan4xr8npdk8tkth62jtpwqg4u0n3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSVZMeGs4WldHLzRkdHdF
            VTRtdExseVlidmtUakJBQVNDUm83YlhVNUdJCnR4NU4rcGVBQzRIajU5bkJ2Tlhz
            SzFWeS95dHdPYVRiT3A2L2pVQUdwQ2MKLS0tIGs2MDNZT3ZWWFZJUUlJUG1DRUVx
            QTRPdkNCV0htOWd2bGJMUC9YaHJiMHMK/MtKYHJ13htFlZ3cLYRHl3l4k1xI14IQ
            bAzByiYM7ZFkTHgr0Rg5Jl1ryjhZ0Az7PJ0DwouZRHy63j/ux29IVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q2qaahrx4chvsa5g7xqwrwk28mld6kn4md8crcrqg046m8yt2efsugl8vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbU1PanVZNlhCbkk0cHNN
            S1VYVG01ZEVBYWo1cWJlNXdlYjJvM1ZoU0h3Ck5CUUVvcVBldHJXWGg4b29kYnQ3
            WEFiQVRRWEFZMW4rUDEwNmlydzlOaVUKLS0tIDZVZXJST2JnNkRHejRzU0FhNXV6
            cWNRbDdCcTV5M2xQWHFVdCtGdi8zUTQK/ooZzXJReNPLiMo5O7ryNSSdFqczuWm4
            BTux6bHB8FRG9/Szl331K5YbxH6MwkY3M9BefxsNb1cT/hGS/dplIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-13T18:17:53Z"
    mac: ENC[AES256_GCM,data:mq6xJvMjqjs8i9y6nghAQMRoZnkORjFcoJcs1F1YSRVDgGB3xHABswlBryu5d/ffMt7mChWQc6x0n30dWqJnqm485lvEuTzWVbDNeW5/75BqyI4MGYdn32uVO6/YW3K0YGjE5PRNNS5s7eCv+CbGqe9son6DnS4DZsOkd9OZG9E=,iv:K7f6B6vnX+M6SJIEiIGQT3A8bRIb6ek3/XhkYgqabJo=,tag:DZBHqvdwennW0axDxhfnmg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
