#!/usr/bin/env lua

-- This is only needed once to install the sketchybar module
-- (or for an update of the module)
-- TODO: replace with nixpkg derivation
os.execute(
	"[ ! -f $HOME/.local/share/sketchybar_lua/sketchybar.so ] && (git clone https://github.com/FelixKratz/SbarLua.git /tmp/SbarLua && cd /tmp/SbarLua/ && make install && rm -rf /tmp/SbarLua/)"
)

-- Add the sketchybar module to the package cpath (the module could be
-- installed into the default search path then this would not be needed)
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

-- Require the sketchybar module
Sbar = require("sketchybar")

Sbar.exec("killall sketchyhelper || sketchyhelper git.felix.sketchyhelper >/dev/null 2>&1 &")

-- Bundle the entire initial configuration into a single message to sketchybar
-- This improves startup times drastically, try removing both the begin and end
-- config calls to see the difference -- yeah..
Sbar.begin_config()
require("init")
Sbar.hotload(true)
Sbar.end_config()

-- Run the event loop of the sketchybar module (without this there will be no
-- callback functions executed in the lua module)
Sbar.event_loop()
