{
  config,
  lib,
  ...
}:
let
  inherit (lib) types mkIf;
  inherit (lib.khanelinix) mkBoolOpt mkOpt;

  cfg = config.khanelinix.environments.home-network;

  nfsMountOptions = "fstype=nfs,rw,resvport,soft,timeo=20,retrans=1";

  autoAustinserverMap = ''
    appdata -${nfsMountOptions} ${cfg.serverHostname}:/mnt/user/appdata
    data -${nfsMountOptions} ${cfg.serverHostname}:/mnt/user/data
    isos -${nfsMountOptions} ${cfg.serverHostname}:/mnt/user/isos
    dropbox -${nfsMountOptions} ${cfg.serverHostname}:/mnt/disks/dropbox
    googledrive -${nfsMountOptions} ${cfg.serverHostname}:/mnt/disks/googledrive
    onedrive -${nfsMountOptions} ${cfg.serverHostname}:/mnt/disks/onedrive
  '';
in
{
  options.khanelinix.environments.home-network = with types; {
    enable = lib.mkEnableOption "home network environment";
    serverHostname = mkOpt str "austinserver.taild8431e.ts.net" "Home server hostname";
    enableNFSMounts = mkBoolOpt true "Enable NFS mounts to home server";
  };

  config = mkIf cfg.enable {
    environment.etc = mkIf cfg.enableNFSMounts {
      auto_austinserver.text = ''
        # Generated by nix-darwin
        ${autoAustinserverMap}
      '';
    };

    system.activationScripts.extraActivation.text = mkIf cfg.enableNFSMounts (
      lib.mkAfter ''
        autoMaster="/etc/auto_master"
        autoMasterEntry="/Volumes/austinserver auto_austinserver -nosuid"
        staleAutoMasterEntry="/mnt auto_austinserver -nobrowse,nosuid"
        staleSyntheticFile="/etc/synthetic.d/khanelinix-mnt"

        echo >&2 "Configuring austinserver autofs mounts..."

        if [ -f "$staleSyntheticFile" ]; then
          /bin/rm -f "$staleSyntheticFile"
          echo >&2 "Removed stale /mnt synthetic mountpoint manifest."
        fi

        if [ ! -f "$autoMaster" ]; then
          /usr/bin/touch "$autoMaster"
        fi

        if /usr/bin/grep -Fxq "$staleAutoMasterEntry" "$autoMaster"; then
          autoMasterTmp="$(/usr/bin/mktemp /tmp/khanelinix-auto-master.XXXXXX)"
          /usr/bin/grep -Fxv "$staleAutoMasterEntry" "$autoMaster" > "$autoMasterTmp" || true
          /bin/cat "$autoMasterTmp" > "$autoMaster"
          /bin/rm -f "$autoMasterTmp"
        fi

        if ! /usr/bin/grep -Fq "$autoMasterEntry" "$autoMaster"; then
          /bin/cp "$autoMaster" "$autoMaster.khanelinix.bak"
          /bin/cat >> "$autoMaster" <<EOF
        $autoMasterEntry
        EOF
        fi

        /bin/mkdir -p /Volumes/austinserver
        /usr/sbin/automount -vc
      ''
    );

    # SSH config for home server is handled in home-manager module
    # to keep it cross-platform
  };
}
