#!/usr/bin/env lua

print("Dynamic Island Starting")

-- This is only needed once to install the sketchybar module
-- (or for an update of the module)
-- TODO: replace with nixpkg derivation when we can, darwin frameworks need to get updated
os.execute(
	"[ ! -f $HOME/.local/share/sketchybar_lua/sketchybar.so ] && (git clone https://github.com/FelixKratz/SbarLua.git /tmp/SbarLua && cd /tmp/SbarLua/ && make install && rm -rf /tmp/SbarLua/)"
)

-- Add the sketchybar module to the package cpath (the module could be
-- installed into the default search path then this would not be needed)
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

print("Installed sketchybar module")
print(package.cpath)

-- Require the sketchybar module
Sbar = require("sketchybar")

print("Loaded sketchybar module")

Sbar.set_bar_name("dynamic-island-sketchybar")

print("Set bar name")

Sbar.exec("killall dynamic-island-helper || dynamic-island-helper git.felix.islandhelper >/dev/null 2>&1 &")

print("Started helper")

-- Bundle the entire initial configuration into a single message to sketchybar
-- This improves startup times drastically, try removing both the begin and end
-- config calls to see the difference -- yeah..
Sbar.begin_config()
require("init")
Sbar.hotload(true)
Sbar.end_config()

-- Run the event loop of the sketchybar module (without this there will be no
-- callback functions executed in the lua module)
Sbar.event_loop()
