{
  config,
  lib,
  ...
}:
let
  cfg = config.khanelinix.programs.terminal.tools.antigravity-cli;

  readOnlyCommands = [
    "ls"
    "find"
    "fd"
    "cat"
    "head"
    "tail"
    "rg"
    "grep"
    "diff"
    "sort"
    "uniq"
    "cut"
    "comm"
    "column"
    "jq"
    "nl"
    "tac"
    "rev"
    "tr"
    "sed -n"
    "od"
    "xxd"
    "hexdump"
    "strings"
    "base64"
    "cksum"
    "md5sum"
    "sha1sum"
    "sha256sum"
    "sha512sum"
    "b2sum"
    "stat"
    "file"
    "wc"
    "tree"
    "realpath"
    "readlink"
    "dirname"
    "basename"
    "du"
    "type"
    "which"
    "whereis"
    "command -v"
    "getconf"
    "printenv"
    "lsof"
    "getent"
    "lsblk"
    "lsusb"
    "lspci"
    "findmnt"
    "nixos-option"
    "statix check"
    "pwd"
    "whoami"
    "id"
    "hostname"
    "uname"
    "date"
    "uptime"
    "env"
    "free"
    "ps"
    "pgrep"
    "ss"
    "df"
    "groups"
    "locale"
    "lscpu"
    "git status"
    "git diff"
    "git log"
    "git show"
    "git branch"
    "git remote"
    "git ls-files"
    "git ls-tree"
    "git blame"
    "git grep"
    "git rev-parse"
    "git describe"
    "git shortlog"
    "git reflog"
    "git cat-file"
    "git show-ref"
    "git for-each-ref"
    "git rev-list"
    "git merge-base"
    "git name-rev"
    "git stash list"
    "git worktree list"
    "git submodule status"
    "git config --get"
    "git config --list"
    "git config -l"
    "nix eval"
    "nix search"
    "nix log"
    "nix path-info"
    "nix flake show"
    "nix flake metadata"
    "nix derivation show"
    "nix why-depends"
    "nix store ls"
    "nix store cat"
    "nix store info"
    "nix config show"
    "nix show-config"
    "nix registry list"
    "nix profile list"
    "nh search"
    "nix-instantiate --parse"
    "nix-store -q"
    "nix-store --query"
    "jj status"
    "jj log"
    "jj diff"
    "jj show"
    "jj evolog"
    "jj op log"
    "jj file list"
    "jj bookmark list"
    "gh auth status"
    "gh pr view"
    "gh pr list"
    "gh pr diff"
    "gh pr checks"
    "gh pr status"
    "gh issue view"
    "gh issue list"
    "gh issue status"
    "gh run view"
    "gh run list"
    "gh repo view"
    "gh release view"
    "gh release list"
    "gh label list"
    "gh search"
  ];

  reviewCommands = [
    "git add"
    "cp"
    "mv"
    "chmod"
    "chown"
    "curl"
    "wget"
    "ssh"
    "scp"
    "rsync"
    "nix build"
    "nix run"
    "nix shell"
    "nixos-rebuild"
    "darwin-rebuild"
    "nh"
    "kill"
    "killall"
    "pkill"
    "build-by-path"
    "why-depends"
    "git commit"
    "git checkout"
    "git switch"
    "git restore"
    "git reset"
    "git stash"
    "git merge"
    "git rebase"
    "git pull"
    "git push"
    "fix-git"
    "systemctl start"
    "systemctl stop"
    "systemctl restart"
    "systemctl reload"
    "systemctl enable"
    "systemctl disable"
    "rm -rf"
    "sudo rm -rf"
    "dd"
    "mkfs"
    "shutdown"
    "reboot"
  ];

  denyCommands = [
    "rm -rf /"
    "rm -rf /*"
    "sudo rm -rf /"
    "sudo rm -rf /*"
  ];
in
{
  config = lib.mkIf cfg.enable {
    programs.antigravity-cli = {
      settings.permissions = {
        allow = map (command: "command(${command})") readOnlyCommands;
        ask = map (command: "command(${command})") reviewCommands;
        deny = map (command: "command(${command})") denyCommands;
      };
    };
  };
}
