name: "Cachix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: khanelinix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix develop
    - run: nix shell nixpkgs#hello --command hello --greeting 'Ok'
