name: Check
permissions:
  contents: read
on: [push, pull_request, workflow_dispatch]
jobs:
  checks:
    name: Check flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v12
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: khanelinix
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Run flake checks
        run: nix flake check --system x86_64-linux --print-build-logs
